import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import getArtifacts from '../solql/getArtifacts'
import { QueryArtifact } from '../solql/QueryArtifact'


export async function getStaticProps() {
  const hardhatArtifacts = await getArtifacts(["Query"]);
  return {
    props: {
      hardhatArtifact: hardhatArtifacts[0]
    }
  };
}


const Home: NextPage = ({hardhatArtifact}) => {

  const { address, isConnected } = useAccount();
  const { connect } = useConnect({
    connector: new InjectedConnector()
  })
  connect();


  const query = new QueryArtifact(hardhatArtifact);
  query.constructAndRun([2,15]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {address}
      </main>
    </div>
  )
}




export default Home
