import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Artifact } from 'hardhat/types'
import serialisedArtifacts from "../solql-artifacts.json";

const Home: NextPage= () => {
  const artifacts: Artifact[] = serialisedArtifacts;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      </main>
    </div>
  )
}




export default Home
